# SonarQube Project Configuration
sonar.projectKey=cake-site-2
sonar.projectName=SP Cakes & Delight
sonar.projectVersion=1.0

# Path to source directories
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.js,src/**/*.spec.js

# Exclusions
sonar.exclusions=node_modules/**,build/**,public/**
sonar.javascript.node.maxstacksize=400

# Encoding
sonar.sourceEncoding=UTF-8
